#!/usr/bin/env python3
"""Hermetic offline replay/stub harness for the TypeSafe decision layer.

Nothing here opens a socket. `install()` replaces `ts_common.TRANSPORT`, so both
route and workflow clients are covered by a single seam, and it also neutralises
`SLEEP`/`MONOTONIC` so retry/deadline tests are instant and deterministic.

Transports
----------
StubTransport      : programmable answers per request (plus scripted HTTP errors)
ReplayTransport    : replays frozen API responses recorded from a real run
RecordingTransport : wraps another transport and records every exchange

Guarantees asserted by the suite:
- TYPESAFE_OFFLINE=1 makes the real network transport raise, even with a key set.
- The production decision log is never written by any harness-driven run.
"""
import json
import os
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
# Frozen, fully SYNTHETIC replay inputs that ship with the repository.
# They are generated by `tests/generate_fixtures.py`; no real corpus, no real
# API transcript and no production log is involved. Override with
# TYPESAFE_FIXTURES_DIR to replay a different frozen set.
FIXTURES_DIR = os.environ.get(
    "TYPESAFE_FIXTURES_DIR", os.path.join(REPO_ROOT, "tests", "fixtures"))
FIXTURE_MANIFEST = os.path.join(FIXTURES_DIR, "MANIFEST.sha256.json")


class FixtureIntegrityError(AssertionError):
    """A frozen replay fixture is missing or no longer matches its manifest hash."""


def verify_fixture_hashes(base=None, manifest=None):
    """Verify frozen replay inputs against their SHA-256 manifest. Raises on drift.

    Returns the list of verified {name, sha256} entries so callers can record
    exactly which bytes a replay consumed.
    """
    import hashlib
    base = base or FIXTURES_DIR
    manifest = manifest or os.path.join(base, "MANIFEST.sha256.json")
    if not os.path.exists(manifest):
        raise FixtureIntegrityError(f"missing_fixture_manifest:{manifest}")
    doc = json.load(open(manifest, encoding="utf-8"))
    verified = []
    for entry in doc["files"]:
        p = os.path.join(base, entry["name"])
        if not os.path.exists(p):
            raise FixtureIntegrityError(f"missing_fixture:{entry['name']}")
        h = hashlib.sha256()
        with open(p, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
        got = h.hexdigest()
        if got != entry["sha256"]:
            raise FixtureIntegrityError(f"fixture_hash_mismatch:{entry['name']}")
        verified.append({"name": entry["name"], "sha256": got})
    return verified


def fixture_provenance(base=None):
    """Content-free provenance record of the frozen replay inputs."""
    base = base or FIXTURES_DIR
    doc = json.load(open(os.path.join(base, "MANIFEST.sha256.json"), encoding="utf-8"))
    note = ""
    prov = os.path.join(base, "provenance.txt")
    if os.path.exists(prov):
        note = open(prov, encoding="utf-8").read().strip()
    return {"root": base, "file_count": doc["file_count"],
            "aggregate_sha256": doc["aggregate_sha256"],
            "manifest_label": doc.get("manifest_label"),
            "provenance": note}


class Clock:
    """Virtual clock: sleep advances time instantly."""

    def __init__(self, start=1000.0):
        self.now = float(start)
        self.slept = []

    def monotonic(self):
        return self.now

    def sleep(self, seconds):
        self.slept.append(round(float(seconds), 6))
        self.now += float(seconds)

    def advance(self, seconds):
        self.now += float(seconds)


class _Base:
    def __init__(self):
        self.requests = []
        self.calls = 0

    def __call__(self, url, body_bytes, headers, timeout):
        self.calls += 1
        body = json.loads(body_bytes.decode("utf-8"))
        self.requests.append({"url": url, "body": body, "timeout": timeout})
        return self.respond(body)

    def respond(self, body):  # pragma: no cover - interface
        raise NotImplementedError

    @staticmethod
    def ok(payload):
        return 200, {"Content-Type": "application/json"}, json.dumps(payload).encode()

    @staticmethod
    def err(status, retry_after=None, payload=None):
        h = {"Content-Type": "application/json"}
        if retry_after is not None:
            h["Retry-After"] = str(retry_after)
        return status, h, json.dumps(payload or {"error": {"status": status}}).encode()

    @property
    def payload_chars(self):
        return sum(len(json.dumps(r["body"]["state"], ensure_ascii=False, separators=(",", ":")))
                   + len(json.dumps(r["body"]["questions"], ensure_ascii=False, separators=(",", ":")))
                   for r in self.requests)


class StubTransport(_Base):
    """Answers questions by key suffix using caller-supplied rules.

    answer_fn(state, questions) -> dict of answers, or None to use `rules`.
    script: list of (status, retry_after) forced responses consumed in order;
            a None entry means "answer normally".
    """

    def __init__(self, answer_fn=None, model="jev-1.13.0", usage=None, script=None):
        super().__init__()
        self.answer_fn = answer_fn
        self.model = model
        self.usage = usage or {"input_tokens": 10, "output_tokens": 2}
        self.script = list(script or [])

    def respond(self, body):
        if self.script:
            item = self.script.pop(0)
            if item is not None:
                status, retry_after = item if isinstance(item, tuple) else (item, None)
                return self.err(status, retry_after)
        state, questions = body.get("state", {}), body.get("questions", {})
        answers = (self.answer_fn(state, questions) if self.answer_fn else None)
        if answers is None:
            answers = {k: {"noul": 0.5, "confidence": 0.9} for k in questions}
        return self.ok({"model": self.model, "answers": answers, "usage": dict(self.usage)})


class ReplayTransport(_Base):
    """Replays a recorded cassette: a list of {request_sha256?, response} entries.

    Strict order replay by default; `by_hash=True` matches on the request body
    hash so chunk reordering is detected instead of silently mismatching.
    """

    def __init__(self, cassette, by_hash=False):
        super().__init__()
        if isinstance(cassette, str):
            with open(cassette, encoding="utf-8") as f:
                cassette = json.load(f)
        self.entries = cassette["exchanges"] if isinstance(cassette, dict) else list(cassette)
        self.by_hash = by_hash
        self.index = 0

    def respond(self, body):
        import hashlib
        if self.by_hash:
            h = hashlib.sha256(json.dumps(body, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
            for e in self.entries:
                if e.get("request_sha256") == h:
                    return self.ok(e["response"])
            raise AssertionError(f"replay_miss:{h[:16]}")
        if self.index >= len(self.entries):
            raise AssertionError("replay_exhausted")
        e = self.entries[self.index]
        self.index += 1
        status = e.get("status", 200)
        if status != 200:
            return self.err(status, e.get("retry_after"))
        return self.ok(e["response"])


class RecordingTransport(_Base):
    def __init__(self, inner):
        super().__init__()
        self.inner = inner
        self.exchanges = []

    def respond(self, body):
        import hashlib
        status, headers, data = self.inner(None, json.dumps(body).encode(), {}, 30)
        self.exchanges.append({
            "request_sha256": hashlib.sha256(json.dumps(body, sort_keys=True, separators=(",", ":")).encode()).hexdigest(),
            "status": status,
            "response": json.loads(data.decode()) if status == 200 else None,
        })
        return status, headers, data

    def save(self, path):
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"version": 1, "exchanges": self.exchanges}, f, indent=1)


class Harness:
    """Context manager installing a transport, a virtual clock and a temp log."""

    def __init__(self, tsc, transport, log_path=None, api_key="test-key-not-real", offline=True):
        self.tsc = tsc
        self.transport = transport
        self.log_path = log_path
        self.api_key = api_key
        self.offline = offline
        self.clock = Clock()
        self._saved = {}

    def __enter__(self):
        t = self.tsc
        self._saved = {"transport": t.TRANSPORT, "sleep": t.SLEEP, "monotonic": t.MONOTONIC,
                       "env": {k: os.environ.get(k) for k in
                               ("TYPESAFE_API_KEY", "TYPESAFE_OFFLINE", "TYPESAFE_DECISION_LOG")}}
        t.set_transport(self.transport)
        t.SLEEP = self.clock.sleep
        t.MONOTONIC = self.clock.monotonic
        if self.api_key is not None:
            os.environ["TYPESAFE_API_KEY"] = self.api_key
        else:
            os.environ.pop("TYPESAFE_API_KEY", None)
        os.environ["TYPESAFE_OFFLINE"] = "1" if self.offline else "0"
        if self.log_path:
            os.environ["TYPESAFE_DECISION_LOG"] = str(self.log_path)
        return self

    def __exit__(self, *exc):
        t = self.tsc
        t.set_transport(self._saved["transport"])
        t.SLEEP = self._saved["sleep"]
        t.MONOTONIC = self._saved["monotonic"]
        for k, v in self._saved["env"].items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
        return False


def child_env(extra=None, log_path=None):
    """Environment for subprocess CLI tests: offline, never the production log."""
    env = dict(os.environ)
    env["TYPESAFE_OFFLINE"] = "1"
    env["TYPESAFE_SYSTEMONE_URL"] = "http://127.0.0.1:9/blocked"
    env["TYPESAFE_DECISION_LOG"] = str(log_path or os.path.join(
        tempfile.gettempdir(), "typesafe-test-log.jsonl"))
    env.update(extra or {})
    return env


def rank_answer_fn(cov=None, inj=None, fit=None, useful=None, default_cov=0.05, default_fit=0.9):
    """Build a stub answer function for rank/shortlist question sets."""
    cov, inj, fit, useful = cov or {}, inj or {}, fit or {}, useful or {}

    def fn(state, questions):
        a = {}
        for k in questions:
            ci = int(k[1:k.index("_")])
            cid = state["candidates"][ci]["id"]
            if k.endswith("_injection"):
                a[k] = {"noul": inj.get(cid, 0.01)}
            elif k.endswith("_fit"):
                a[k] = {"noul": fit.get(cid, default_fit)}
            elif k.endswith("_useful"):
                a[k] = {"noul": useful.get(cid, fit.get(cid, default_fit))}
            else:
                ri = int(k.rsplit("_r", 1)[1])
                a[k] = {"noul": cov.get(cid, {}).get(ri, default_cov)}
        return a
    return fn


def route_answer_fn(choice="max", confidence=0.9, parallel=0.2, complexity=1.0, consequence=1.0, delegation=0.5):
    def fn(state, questions):
        return {"executor": {"choice": choice, "confidence": confidence},
                "delegation_value": {"noul": delegation},
                "parallelizable": {"noul": parallel},
                "complexity": {"score": complexity},
                "consequence": {"score": consequence}}
    return fn


def verify_answer_fn(status="complete", confidence=0.9, evidence=None):
    def fn(state, questions):
        a = {}
        for k in questions:
            if k.endswith("_status"):
                a[k] = {"choice": status, "confidence": confidence}
            elif k.endswith("_evidence") and evidence is not None:
                a[k] = {"noul": evidence}
        return a
    return fn


def triage_answer_fn(impact="low", reversible=0.9, intent=0.9):
    def fn(state, questions):
        return {"impact": {"choice": impact, "confidence": 0.9},
                "reversible": {"noul": reversible},
                "intent_specific": {"noul": intent}}
    return fn


def frozen_shortlist_cassette(path=None, verify_hashes=True):
    """Build a cassette from the frozen shortlist run's per-candidate scores.

    The frozen artifact stores aggregated ranking rows rather than raw API
    exchanges, so this reconstructs the answer payload each chunk would have
    produced. It reproduces the ranking rows bit-exactly, which is what the
    deterministic selection layer consumes.

    Reads the SYNTHETIC frozen fixtures shipped in `tests/fixtures` by default
    and verifies their SHA-256 against `MANIFEST.sha256.json` at runtime, so a
    modified input can never masquerade as the frozen baseline (audit P2 replay
    provenance).
    """
    base = path or FIXTURES_DIR
    if verify_hashes:
        verify_fixture_hashes(base)
    out = json.load(open(os.path.join(base, "rank_shortlist_output.json"), encoding="utf-8"))["result"]
    by_id = {r["id"]: r for r in out["ranking"]}

    def fn(state, questions):
        a = {}
        for k in questions:
            ci = int(k[1:k.index("_")])
            cid = state["candidates"][ci]["id"]
            row = by_id[cid]
            if k.endswith("_fit"):
                a[k] = {"noul": row["fit"]}
            elif k.endswith("_useful"):
                a[k] = {"noul": row["useful"]}
            elif k.endswith("_injection"):
                a[k] = {"noul": row["injection"]}
            else:
                ri = int(k.rsplit("_r", 1)[1])
                rid = list(row["coverage"])[ri]
                a[k] = {"noul": row["coverage"][rid]}
        return a
    return StubTransport(answer_fn=fn, model="jev-1.13.0",
                         usage={"input_tokens": 0, "output_tokens": 0})
